### ISSUE TITLE
TwinklyHaHa Dockerfile and GCP process

### ISSUE THREAD

**Issue by sparrell** [sparrell/SbomPoc-sFractal#34]

**Comment by sparrell** [comment]
has bug.
if do:
make push-and-serve-gcp instance-name=dendritic
error out with:
Step 16/25 : RUN mix phx.digest && mix release
 ---> Running in a7cff629bf37
** (RuntimeError) environment variable DATABASE_URL is missing.
For example: ecto://USER:PASS@HOST/DATABASE

    (stdlib 3.12.1) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib 3.12.1) erl_eval.erl:449: :erl_eval.expr/5
    (elixir 1.10.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
    (mix 1.10.4) lib/mix/config.ex:158: anonymous fn/2 in Mix.Config.__import__!/2
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.10.4) lib/mix/config.ex:157: Mix.Config.__import__!/2
The command '/bin/sh -c mix phx.digest && mix release' returned a non-zero code: 1
make: *** [push-image-gcp] Error 1

If include env variables on command line, still get same error. TwinklyMaha had similar issues so TwinklyHaha probably needs same fix

**Comment by sparrell** [comment]
Issue above was operator error. I needed to put dburl in secrets file directly, not as env variable (since docker image is different env). Tested and worked.
